version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend/src:/app/src
    command: npm run dev
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/webpack.config.js:/app/webpack.config.js
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge